name: Paths example

# **What it does**: If someone changes some files in the open repo, we prevent the pull request from merging.
# **Why we have it**: Some files can only be changed in the internal repository for security and workflow reasons.
# **Who does it impact**: Open source contributors.

on:
  # Needed in lieu of `pull_request` so that PRs from a fork can be notified of unallowed changes.
  pull_request_target:
    paths:
      - '!src/**'
      - 'content/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Output
        run: echo "Hello World"

      
