name: Check unallowed file changes

# **What it does**: If someone changes some files in the open repo, we prevent the pull request from merging.
# **Why we have it**: Some files can only be changed in the internal repository for security and workflow reasons.
# **Who does it impact**: Open source contributors.

on:
  # Needed in lieu of `pull_request` so that PRs from a fork can be notified of unallowed changes.
  pull_request_target:

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          output_renamed_files_as_deleted_and_added: true

      - name: List all added files
        env:
          ADDED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: echo $ADDED_FILES

